spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: bloguser
    password: blogpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 65eb26c055f1db06ca30ee63aa222eb85202f183699e520b4b230f5d5a62d804
  expiration: 86400000
